# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:19
from __future__ import unicode_literals

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_slot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slot_number',
            field=models.IntegerField(blank=True, default=cars.models.get_slot_number, null=True),
        ),
    ]
