# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_slot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slot_number',
        ),
    ]
